local _, addonTable = ...

local GetSpellInfo = GetSpellInfo

addonTable.localization.msg['enUS'] = {
    -- [BWD] Berserk
    ["[BWD] Berserk"] = 'Berserk',

    -- [BWD] Icons
    ["[Nefarian] Stolen Power Buff"]                = "dmg/heal",
    ["[Nefarian] Free Your Mind Buff"]              = "+120%\nspeed",
    ["[Nefarian] Shadow of Cowardice Debuff"]       = "shadow\ndmg taken",
    ["[Maloriak] Dark Sludge Debuff"]               = "Get Out",
    ["[Maloriak] Engulfing Darkness Debuff"]        = "-100%\ninc. heal",
    ["[Maloriak] Steal Remedy"]                     = "Steal\nBoss Hot",
    ["[Atramedes] Pestered!"]                       = "Targetted\nby Imp",
    ["[Atramedes] Searing Flame"]                   = "dmg\ntaking",
    ["[Atramedes] Roaring Flame Debuff"]            = "Fire DoT",
    ["[Chimaeron] Caustic Slime"]                   = "-75% hit",
    ["[Chimaeron] Missing Finkle's Mixture Debuff"] = "Missing\nAntideadge",
    ["[Chimaeron] Mocking Shadows (2nd phase)"]     = "2K Damage\nPer Second",
    ["[Chimaeron] Mortality (2nd phase)"]           = "Heal",
    ["[ODS] Power Generator Debuff"]                = "Damage",
    ["[ODS] Power Generator Missing [DPS]"]         = "Go to\nBlue Pool",
    ["[ODS] Steal Converted Power"]                 = "Steal",
    ["[ODS] Chemical Cloud Debuff"]                 = "increased\ndamage\ntaking",
    ["[ODS] Soaked in Poison Debuff"]               = "Poison\nDispel",
    ["[Magmaw] Parasitic Infection Debuff"]         = "Parasite\nInside",
    ["[Trash] Debuff - Magma (BWD)"]                = "dmg\ntaking",
    ["[Trash] Debuff - Flame Buffet_1"]             = 'Fire DoT',
    ["[Trash] Debuff - Flame Buffet_2"]             = 'damage\ntaking',
    ["[Trash] Debuff - Shadowflame"]                = "Shadow\nDoT",
    ["[Trash] Debuff - Flash Bomb"]                 = "Stunned",
    ["[Trash] Debuff - Burden of the Crown_1"]      = "Taking dmg\non hit",
    ["[Trash] Debuff - Burden of the Crown_2"]      = '+Damage',

    -- [BWD] Big Icons
    ["[Nefarian] Debuff - Explosive Cinders"]       = "Be Ready\nto run Out",
    ["[Nefarian] Debuff - Dominion"]                = "Mind Control",
    ["[Maloriak] Debuff - Flash Freeze"]            = "Frozen",
    ["[Maloriak] Debuff - Biting Chill"]            = "Stay Spread",
    ["[Maloriak] Debuff - Consuming Flames"]        = "Get Out",
    ["[Artamedes] Debuff - Tracking"]               = "Kite Beam",
    ["[Artamedes] Debuff - Boss Stun"]              = "Boss Stunned",
    ["[Atramedes] Noisy"]                           = "Reduce\nsound assap!",
    ["[ODS] Overcharged Power Generator Debuff_1"]  = "Run Out\nOf Pool",
    ["[ODS] Overcharged Power Generator Debuff_2"]  = "+100% dmg",
    ["[ODS] Debuff - Shadow Infusion"]              = "Prepare\nTo Stack",
    ["[ODS] Debuff - Shadow Conductor"]             = "Stack\nWith Raid",
    ["[ODS] Debuff - Lightning Conductor"]          = "Get Out",
    ["[ODS] Debuff - Encasing Shadow"]              = "Immobalized",
    ["[ODS] Debuff - Acquiring Target"]             = "Face Boss\nAway",
    ["[ODS] Debuff - Fixated"]                      = "Fixated by\nPoisonBomb",
    ["[Magmaw] Debuff - Mangle"]                    = "Grabbed",
    ["[Magmaw] Debuff - Shadow Breath"]             = "Stay Out",
    ["[Trash] Debuff - Piercing Grip"]              = "Grabbed",
    ["[Trash] Debuff - Aura of Dead"]               = "Stay Out",

    -- [BWD] Progress Bars
    ["[Nefarian] Nefarian Roleplay"]                = "Nefarian Roleplay",
    ["[Nefarian] Nefarian Landing"]                 = "Nefarian Landing",
    ["[Nefarian] Electrocute"]                      = "Electrocute (Raid Damage)",
    ["[Maloriak] Debilitating Slime"]               = "Mobs taking increased damage",
    ["[Maloriak] Engulfing Darkness_1"]             = "Free to Heal",
    ["[Maloriak] Engulfing Darkness_2"]             = "-100% heal",
    ["[Maloriak] Arcane Storm"]                     = "Raid Damage",
    ["[Maloriak] Release Abberation"]               = "Release Abberation",
    ["[Atramedes] Air Phase Duration"]              = "Air Phase",
    ["[Atramedes] Searing Flames"]                  = "Huge Raid Damage",
    ["[Chimaeron] Reroute Power"]                   = "Robot Deactivation",
    ["[Chimaeron] Fight Start"]                     = "Fight Start",
    ["[ODS] Shadow Infusion"]                       = "Stack on",
    ["[ODS] Incineration Security Measure"]         = "Raid Damage",
    ["[ODS] Poison Protocol"]                       = "Spawning Poison Bombs",
    ["[Magmaw] Lava Spew [Healer]"]                 = "Raid Damage",
    ["[Magmaw] Armageddon Cast"]                    = "Dont stay near Construct!",
    ["[Magmaw] Head Exposed"]                       = "BURST BOSS",
    ["[Magmaw] Molten Tantrum Buff"]                = "boss damage increased",
    ["[Trash] Shadowflame Cast"]                    = "Dodge Frontal",
    ["[Trash] Sacrifice Debuff"]                    = "Interrupt",
    ["[Trash] Whirlwind Cast"]                      = "Dodge Whirlwind",

    -- [BWD] Alternative Powers
    ["[Atramedes] Alternative Power - Loud"]        = "Sound Level",
    ["[Maloriak] Counter - Abberations_1"]          = "Dark Phase",
    ["[Maloriak] Counter - Abberations_2"]          = "Blue Phase",
    ["[Maloriak] Counter - Abberations_3"]          = "Red Phase",
    ["[Maloriak] Counter - Abberations_4"]          = "Green Phase",

    -- [BWD] Little Progress Bars
    ["[Nefarian] Shadowblaze Spark PreWarning"]     = GetSpellInfo(81031),

    -- [BWD] Cooldowns
    ["[Nefarian] CD - Shadowblaze Spark"]           = GetSpellInfo(81031),
    ["[Nefarian] CD - Explosive Cinders"]           = GetSpellInfo(79339),
    ["[Nefarian] CD - Dominion"]                    = "Mind Control",
    ["[Nefarian] CD - Lightning Discharge"]         = GetSpellInfo(77939),
    ["[Nefarian] CD - Shadowflame Breath [Tank]"]   = "Breath",
    ["[Nefarian] CD - Tail Lash [Tank]"]            = GetSpellInfo(77827),
    ["[Maloriak] Next Phase Dark (Heroic)"]         = "Dark Phase",
    ["[Maloriak] Next Phase Blue or Red"]           = "Blue/Red Phase",
    ["[Maloriak] Next Phase Blue"]                  = "Blue Phase",
    ["[Maloriak] Next Phase Red"]                   = "Red Phase",
    ["[Maloriak] Next Phase Green"]                 = "Green Phase",
    ["[Maloriak] CD - Arcane Storm"]                = GetSpellInfo(77896),
    ["[Maloriak] CD - Release Abberation"]          = GetSpellInfo(77569),
    ["[Maloriak] CD - Flash Freeze"]                = GetSpellInfo(77699),
    ["[Maloriak] CD - Debilitating Slime"]          = "+Damage on Enemies",
    ["[Maloriak] CD - Scorching Blast"]             = "Raid Damage",
    ["[Maloriak] CD - Consuming Flames"]            = GetSpellInfo(77786),
    ["[Maloriak] CD - Magma Jets"]                  = "Dodge Frontal",
    ["[Maloriak] CD - Absolute Zero"]               = "Frost Orbs",
    ["[Maloriak] CD - Engulfing Darkness"]          = "Fixated Frontal",
    ["[Atramedes] CD - Air Phase"]                  = "Air Phase",
    ["[Atramedes] CD - Searing Flames"]             = "Huge Raid Damage",
    ["[Atramedes] CD - Sonic Breath"]               = "Fixated Frontal",
    ["[Atramedes] CD - Modulation"]                 = "Raid Damage",
    ["[Atramedes] CD - Sonar Pulse"]                = "Bad Circles",
    ["[Chimaeron] CD - Massacre"]                   = "Health Drop",
    ["[Chimaeron] CD - Systems Failure"]            = GetSpellInfo(88853),
    ["[Chimaeron] CD - Break [Tank]"]               = GetSpellInfo(82881),
    ["[Chimaeron] CD - Caustic Slime"]              = GetSpellInfo(82935),
    ["[ODS] CD - Next Activation"]                  = "Next Activation",
    ["[ODS] CD - Nefarian Special Ability"]         = "Nefarian Special",
    ["[ODS] CD - Power Generator (Arcanotron)"]     = "Damage Pool",
    ["[ODS] CD - Lightning Conductor (Electron)"]   = GetSpellInfo(79888),
    ["[ODS] CD - Chemical Bomb (Toxitron)"]         = GetSpellInfo(80157),
    ["[ODS] CD - Poison Protocol (Toxitron)"]       = "Oozes Spawn",
    ["[ODS] CD - Incineration Security Measure (Magmatron)"] = "Raid Damage",
    ["[ODS] CD - Acquiring Target (Magmatron)"]     = "Fixated Frontal",
    ["[Magmaw] CD - Pillar of Flame"]               = GetSpellInfo(78006),
    ["[Magmaw] CD - Inferno"]                       = "Big Add",
    ["[Magmaw] CD - Lava Spew"]                     = "Raid Damage",
    ["[Magmaw] CD - Mangle"]                        = GetSpellInfo(89773),
    ["[Trash] CD - Chain Lightning"]                = GetSpellInfo(80646),
    ["[Trash] CD - Drakonid Rush"]                  = GetSpellInfo(79630),
    ["[Trash] CD - Enrage"]                         = GetSpellInfo(80084),
    ["[Trash] CD - Piercing Grip"]                  = GetSpellInfo(80145),
    ["[Trash] CD - Shadowflame"]                    = GetSpellInfo(79921),
    ["[Trash] CD - Laser Strike"]                   = GetSpellInfo(81063),
    ["[Trash] CD - Flash Bomb"]                     = GetSpellInfo(81056),

    -- [BWD] Warnings
    ["[Nefarian] W - Phase 2"]                      = "Phase",
    ["[Nefarian] W - Phase 3"]                      = "Phase",
    ["[Nefarian] W - Explosive Cinders"]            = GetSpellInfo(79339),
    ["[Nefarian] W - Dominion"]                     = "Mind Control",
    ["[Maloriak] W - Absolute Zero"]                = "Orbs Spawned",
    ["[Maloriak] W - Consuming Flames"]             = GetSpellInfo(77786),
    ["[Maloriak] W - Phase 2"]                      = "Phase",
    ["[Maloriak] W - Phase 2 Soon"]                 = "Phase",
    ["[Maloriak] W - Red Phase"]                    = "Red Phase",
    ["[Maloriak] W - Blue Phase"]                   = "Blue Phase",
    ["[Maloriak] W - Green Phase"]                  = "Green Phase",
    ["[Maloriak] W - Dark Phase"]                   = "Dark Phase",
    ["[Atramedes] W - Shield Used By"]              = "Shield used",
    ["[Atramedes] W - Tracking"]                    = GetSpellInfo(78092),
    ["[Atramedes] W - Air Phase"]                   = "Air Phase",
    ["[Chimaeron] W - Phase 2"]                     = "Phase",
    ["[Chimearon] W - Phase 2 Soon"]                = "Phasing in",
    ["[Chimaeron] W - Break [Tank]"]                = GetSpellInfo(82881),
    ["[Chimaeron] W - Double Attack [Tank]"]        = GetSpellInfo(88826),
    ["[ODS] W - Boss Activated"]                    = "Activated",
    ["[ODS] W - Acquiring Target"]                  = "Frontal on",
    ["[ODS] W - Lightning Conductor"]               = "Stay away from",
    ["[ODS] W - Power Generator"]                   = "Stay in Blue Pool",
    ["[Trash] W - Laser Strike"]                    = "Dont stay in void zone",
    ["[Trash] W - Flash Bomb"]                      = "Dont stay in void zone",
    ["[Trash] W - Enrage"]                          = GetSpellInfo(80084),
    ["[Trash] W - Sacrifice"]                       = "To be executed",

    -- [BWD] Special Warnings
    ["[Nefarian] GTFO - Shadowblaze"]               = "GTFO",
    ["[Nefarian] Shadowblaze Spark"]                = GetSpellInfo(81031),
    ["[Maloriak] GTFO - Dark Sludge"]               = "GTFO",
    ["[Maloriak] SW - Remedy Dispel"]               = "DISPEL",
    ["[Atramedes] SW - Sonic Breath"]               = GetSpellInfo(78075),
    ["[Atramedes] SW - Searing Flames"]             = GetSpellInfo(77840),
    ["[Atramedes] SW - Sonar Pulse"]                = "AVOID CIRCLES",
    ["[Atramedes] SW - Switch on Imp"]              = "SWITCH ON IMP",
    ["[Chimaeron] SW - Systems Failure"]            = GetSpellInfo(88853),
    ["[Chimaeron] SW - Double Attack [Tank]"]       = GetSpellInfo(88826),
    ["[ODS] SW - GTFO"]                             = "GTFO",
    ["[ODS] SW - Stop Attacking"]                   = "STOP ATTACKING",
    ["[ODS] SW - Power Generator @ Boss [Tank]"]    = "MOVE BOSS",
    ["[Magmaw] SW - Jump Now"]                      = "JUMP NOW",
    ["[Magmaw] SW - Jump on Head Countdown"]        = "JUMP ON HEAD",
    ["[Magmaw] SW - Pillar of Flame"]               = "WATCH YOUR FEET! WORMS",
    ["[Magmaw] SW - Inferno"]                       = "BIG ADD",
    ["[Magmaw] SW - GTFO: Ignition"]                = "GTFO",
    ["[Trash] GTFO - Flame Breath"]                 = "GTFO",
    ["[Trash] GTFO - Laser Strike"]                 = "GTFO",
    ["[Trash] GTFO - Flash Bomb"]                   = "GTFO",

    -- [BWD] Circled Textures
    ["[Nefarian] Circled Texture"]                  = "Mind Control Soon",
    ["[Maloriak] Circled Texture_1"]                = "Dark Phase Soon",
    ["[Maloriak] Circled Texture_2"]                = "Blue / Red Phase Soon",
    ["[Maloriak] Circled Texture_3"]                = "Blue Phase Soon\nPrepare to Spread Out!",
    ["[Maloriak] Circled Texture_4"]                = "Red Phase Soon\nPrepare to Stack!",
    ["[Maloriak] Circled Texture_5"]                = "Green Phase Soon",
    ["[Maloriak] Circled Texture_6"]                = "Rotate Boss!",
    ["[Chimaeron] Circled Texture_1"]               = "Health Drop Cast Soon",
    ["[Chimaeron] Circled Texture_2"]               = "Health Drop",
    ["[Chimaeron] Circled Texture_3"]               = "Fight Start",
    ["[Atramedes] Circled Texture_1"]               = "Frontal Soon",
    ["[Atramedes] Circled Texture_2"]               = "Ground Phase",
    ["[ODS] Circled Texture_1"]                     = "Death Grip",
    ["[ODS] Circled Texture_2"]                     = "Explosion! Run Out!",
    ["[Magmaw] Circled Texture"]                    = "Pillar Flame Soon",
    ["[Trash] Circled Texture"]                     = "Frontal Soon",

    -- [BWD] @Nameplates
    ["[Magmaw] Nameplate Text - Targetted by Worm"] = "Chasing You",

    -- [T4W] Berserking
    ["[BWD] Berserk"] = 'Berserk',

    -- [T4W] Icon
    ["[Al'Akir] Debuff - Acid Raid"]                              = "dmg\nper sec",
    ["[Al'Akir] Buff - Eye of the Storm"]                         = "speed",
    ["[Conclave] Debuff - Hurricane"]                             = "+haste",
    ["[Conclave] Debuff - Ice Path"]                              = "Move Out",
    ["[Conclave] Debuff - [Anshal] Toxic Spores"]                 = "DoT",
    ["[Conclave] Debuff - [Anshal] Withering Winds (Alone)_1"]    = "-100%\nheal",
    ["[Conclave] Debuff - [Anshal] Withering Winds (Alone)_2"]    = "Anshal",
    ["[Conclave] Debuff - [Rohash] Deafing Winds (Alone)_1"]      = "Silenced",
    ["[Conclave] Debuff - [Rohash] Deafing Winds (Alone)_2"]      = "Rohash",
    ["[Conclave] Debuff - [Nezir] Chilling Winds (Alone)_1"]      = "-500%\nhaste",
    ["[Conclave] Debuff - [Nezir] Chilling Winds (Alone)_2"]      = "Nezir",
    ["[T4W] Debuff - Jet Stream"]                                 = "Streams\nCooldown",

    -- [T4W] Big Icons
    ["[Al'Akir] Debuff - Lightning Rod"]        = "Fly Away!",
    ["[Al'Akir] Debuff - Ice Storm"]            = "Run Out",
    ["[Al'Akir] Debuff - Electrocute"]          = "Go to\nMelee Range",
    ["[Al'Akir] Debuff - Squall Line"]          = "Avoid Winds",
    ["[Conclave] Debuff - Soothing Breeze"]     = "Run Out",

    -- [T4W] Progress Bars
    ["[Al'Akir] Lightning Rod"]                = "doing AoE damage",
    ["[Al'Akir] Feedback"]                     = "Damage on Boss",
    ["[Conclave] Special"]                     = "Special Ability",
    ["[Conclave] [Rohash] Wind Blast"]         = GetSpellInfo(86193),

    -- [T4W] Little Progress Bars
    ["[Conclave] Anfall Revive"]         = "Anshal Revive",
    ["[Conclave] Nezir Revive"]          = "Nezir Revive",
    ["[Conclave] Rohash Revive"]         = "Rohash Revive",
    ["[Al'Akir] Next Acid Rain"]         = GetSpellInfo(88301),

    -- [T4W] Cooldowns
    ["[Al'Akir] CD - Ice Storm"]                            = "Blizzards",
    ["[Al'Akir] CD - Wind Burst"]                           = "Knockback",
    ["[Al'Akir] CD - Squad Line"]                           = "Tornados",
    ["[Al'Akir] CD - Stormling"]                            = "Stormling Add",
    ["[Al'Akir] CD - Lightning Clouds"]                     = GetSpellInfo(89588),
    ["[Al'Akir] CD - Lightning Rod"]                        = "Debuff (Fly Out)",
    ["[Conclave] CD - Special"]                             = "Special Ability",
    ["[Conclave] CD - [Anshal] Soothing Breeze"]            = "Green Circle",
    ["[Conclave] CD - [Anshal] Nurture"]                    = "Small Adds",
    ["[Conclave] CD - [Anshal] Toxic Spores"]               = GetSpellInfo(86281),
    ["[Conclave] CD - [Nezir] Wind Chill"]                  = "Raid Damage",
    ["[Conclave] CD - [Nezir] Ice Patch"]                   = GetSpellInfo(86111),
    ["[Conclave] CD - [Nezir] Perma Frost"]                 = "Frontal Target",
    ["[Conclave] CD - Wind Blast"]                          = GetSpellInfo(86193),
    ["[Conclave] CD - Storm Shield"]                        = GetSpellInfo(93059),

    -- [T4W] Circled Textures
    ["[Conclave] Circled Texture_1"]                        = "Go behind the boss!",
    ["[Conclave] Circled Texture_2"]                        = "Special Ability Soon",
    ["[Al'Akir] Circled Texture_1"]                         = "Knockback",
    ["[Al'Akir] Circled Texture_2"]                         = GetSpellInfo(89588),

    -- [T4W] Warnings
    ["[Al'Akir] W - Phase 3"]                            = "Phase",
    ["[Al'Akir] W - Phase 2"]                            = "Phase",
    ["[Al'Akir] W - Phase 2 Soon"]                       = "Phasing in",
    ["[Al'Akir] W - Phase 3 Soon"]                       = "Phasing in",
    ["[Al'Akir] W - [Phase 1] Ice Storm"]                = "Watch Blizzards!",
    ["[Al'Akir] W - [Phase 1/2] Squad Line"]             = "Watch Tornados!",
    ["[Al'Akir] W - [Phase 2] Stormling"]                = "Stormling Spawned",
    ["[Al'Akir] W - [Phase 2] Feedback"]                 = "Damage on Boss",
    ["[Al'Akir] W - [Phase 3] Lightning Rod"]            = GetSpellInfo(89668),
    ["[Conclave] W - [Anshal] Nurture"]                  = "Small Adds",
    ["[Conclave] W - [Nezir] Ice Patch"]                 = "Dont stay in Ice Patches",
    ["[Conclave] W - [Anshall] Toxic Spores"]            = GetSpellInfo(86281),

    -- [T4W] Special Warnings
    ["[Al'Akir] SW - [Phase 3] Short Distance"]           = "SHORT FLIGHT",
    ["[Al'Akir] SW - [Phase 3] Long Distance"]            = "LONG FLIGHT",
    ["[Al'Akir] SW - Wind Burst"]                         = GetSpellInfo(87770),
    ["[Al'Akir] SW - GTFO [Lightning Clouds]"]            = "GTFO",
    ["[Al'Akir] SW - GTFO [Ice Storm]"]                   = "GTFO",
    ["[Al'Akir] SW - Lightning Rod_1"]                    = GetSpellInfo(89668),
    ["[Al'Akir] SW - Lightning Rod_2"]                    = "ON YOU",
    ["[Conclave] SW - GTFO"]                              = "GTFO",
    ["[Conclave] SW - [Rohash] Storm Shield"]             = GetSpellInfo(93059),
    ["[Conclave] SW - [Rohash] Summon Tornados"]          = "WATCH TORNADOS!",
    ["[Conclave] SW - [Rohash] Wind Blast"]               = "AVOID FRONTAL",
    ["[Conclave] SW - [Anshal] Move Boss"]                = "BOSS INSIDE THE CIRCLE",

    -- Bastion [Berserk]
    ["[Bastion] Berserk CD"] = "Berserk",

    -- Bastion [Icons]
    ["[Sinestra] Buff - Fiery Barrier_01"]                  = "Missing\nShield",
    ["[Sinestra] Buff - Fiery Barrier_02"]                  = "-99%\nshadow\ndamage\ntaking",
    ["[Sinestra] Buff - Essence of the Red"]                = "+100% haste",
    ["[Chogal] Debuff - [Phase 2] Debilitating Beam_01"]    = "-75% healing\n-75% damage",
    ["[Chogal] Debuff - [Phase 2] Debilitating Beam_02"]    = "Eyes on you",
    ["[Council] Debuff - [Phase 1] Water Bomb_01"]          = "-25% speed",
    ["[Council] Debuff - [Phase 1] Water Bomb_02"]          = "Expose\nFire Dmg",
    ["[Council] Debuff - [Phase 1] Heart of Ice"]           = "Melees!",
    ["[Council] Debuff - [Phase 1] Burning Blood"]          = "Ranges!",
    ["[Council] Buff - [Phase 1] Frost Imbued"]             = "+Damage\nIgnacious",
    ["[Council] Buff - [Phase 1] Flame Imbued"]             = "+Damage\nFeludius",
    ["[Council] Debuff - [Phase 2] Magnetic Pull"]          = "-50%\nspeed",
    ["[Council] Debuff - [Phase 3] Gravity Crush"]          = "Stunned",
    ["[T&V] Twilight Zone Debuff"]                          = "shadow\ndmg taking",
    ["[Halfus] Furious Roar Debuff"]                        = "Stunned",
    ["[Trash] Debuff - Shockwave"]                          = "Stunned",
    ["[Trash] Debuff - Entomb"]                             = "Expose to\nWinds",
    ["[Trash] Debuff - Rending Gale"]                       = "Expose to\nEarth",
    ["[Trash] Debuff - Dark Pool"]                          = "Dont stay\nin pools",
    ["[Trash] Debuff - Vaporize"]                           = "-100%\narmor",
    ["[Trash] Debuff - Cold-Touched"]                       = "immune\nto fire",
    ["[Trash] Debuff - Tremors"]                            = "Move out",
    ["[Trash] Debuff - Stasis Strike"]                      = "Stunned",
    ["[Trash] Debuff - Soul Blade"]                         = "DoT",
    ["[Trash] Debuff - Phased Burn"]                        = "Targetted\nby well",
    ["[Trash] Debuff - Magma [Bastion]"]                    = "dmg\ntaking",

    -- Bastion [Big Icons]
    ["[Sinestra] Orb Chasing You"]                      = "Check Orb?",
    ["[Sinestra] Debuff - Wrack"]                       = "Wrack DoT",
    ["[Chogal] Debuff - Worshipping"]                   = "Mind\nControlled",
    ["[Chogal] Debuff - Corruption Absolute"]           = "+100% damage\n-100% heal",
    ["[Chogal] Debuff - Corruption Malformation"]       = "Be Spread",
    ["[Chogal] Debuff - Corruption Accelerated"]        = "Dispel\nAsap",
    ["[Council] Debuff - [Phase 1] Static Overload_01"] = "Spread Out",
    ["[Council] Debuff - [Phase 1] Static Overload_02"] = "Find {rt2}",
    ["[Council] Debuff - [Phase 1] Gravity Core_01"]    = "Spread Out",
    ["[Council] Debuff - [Phase 1] Gravity Core_02"]    = "Find {rt6}",
    ["[Council] Debuff - [Phase 2] Lightning Rod_01"]   = GetSpellInfo(83099),
    ["[Council] Debuff - [Phase 2] Lightning Rod_02"]   = "Run Out",
    ["[Council] Debuff - [Phase 2] Lightning Rod_03"]   = "Can go in",
    ["[Council] Debuff - [Phase 2] Frost Beacon"]       = "Kite Orb\nTo Fire!",
    ["[Council] Debuff - Frozen"]                       = "Frozen",
    ["[T&V] Debuff - Blackout"]                         = "Stack with\nthe raid!",
    ["[T&V] Debuff - Meteor"]                           = "Stack with\nthe raid!",
    ["[T&V] Debuff - Exploding"]                        = "Spread out\n or\n stop casting",

    -- Bastion [Alternative Power]
    ["[Chogal] Corruption Blood (Alternate Power)"]     = "Corruption Blood",
    ["[Sinestra] [Phase 2] Calen - Health"]             = "Calen`s Health",
    ["[Sinestra] [Phase 2] Sinestra Mana Barrier"]      = "Sinestra`s Mana",

    -- Bastion [Progress Bars]
    ["[Sinestra] Shadow Orbs Duration"]                 = "Shadow Orbs Duration",
    ["[Sinestra] Twilight Extinction Duration"]         = "-99% Boss Damage",
    ["[Sinestra] Mana Barrier"]                         = "Mana Shielding",
    ["[Chogal] Empowered Shadows Buff (Healers)"]       = "Raid Damage",
    ["[Chogal] Flaming Destruction"]                    = "Flames on Attack",
    ["[Chogal] Phasing"]                                = "Phasing",
    ["[Council] Glaciate Cast"]                         = "Huge Raid Damage",
    ["[Council] Gravity Crush"]                         = GetSpellInfo(84948),
    ["[T&V] Blackout Duration"]                         = "Split damage on",
    ["[T&V] Devouring Flames Cast"]                     = "Move behind the boss!",
    ["[Halifus] Scorching Breath Duration_01"]          = "Raid Damage",
    ["[Halifus] Scorching Breath Duration_02"]          = GetSpellInfo(83855),
    ["[Halifus] Furious Roar"]                          = "Stuns",
    ["[Halifus] Fireball Barrage"]                      = GetSpellInfo(83706),

    -- Bastion [Little Progress Bars]
    ["[Sinestra] Egg Weaken Duration"]                  = "Eggs Weaken",
    ["[Halfus] Scorching Breath Incoming [Healer]"]     = GetSpellInfo(83855),
    
    -- Bastion [Cooldowns]
    ["[Sinestra] CD - [Phase 1] Whelps"]                                = "Whelps",
    ["[Sinestra] CD - [Phase 1] Flame Breath"]                          = GetSpellInfo(90125),
    ["[Sinestra] CD - [Phase 1] Shadow Orbs"]                           = "Shadow Orb",
    ["[Chogal] CD - [Phase 1] Worship"]                                 = "Mind Control",
    ["[Chogal] CD - [Phase 1] Flame Orders_01"]                         = "Fire Elemental",
    ["[Chogal] CD - [Phase 1] Flame Orders_02"]                         = "Add Spawn in",
    ["[Chogal] CD - [Phase 1] Shadow Orders_01"]                        = "Shadow Elemental",
    ["[Chogal] CD - [Phase 1] Shadow Orders_02"]                        = "Add Spawn in",
    ["[Chogal] CD - [Phase 1] Fury [Tank/Healer]"]                      = GetSpellInfo(82524),
    ["[Chogal] CD - [Phase 1] Adherent"]                                = "Big Add",
    ["[Chogal] CD - [Phase 1] Fester Blood"]                            = GetSpellInfo(82299),
    ["[Council] CD - [Phase 1] Glaciate (Feludius)"]                    = "Raid Damage",
    ["[Council] CD - [Phase 1] Hydro Lance (Feludius) [Healer]"]        = "Target Damage",
    ["[Council] CD - [Phase 1] Water Bomb (Feludius)"]                  = GetSpellInfo(82699),
    ["[Council] CD - [Phase 1] Aegis of Flames (Ignacious)"]            = "Shield",
    ["[Council] CD - [Phase 1] Gravity Core (Inactive - Arion)"]        = GetSpellInfo(92075),
    ["[Council] CD - [Phase 1] Static Overload (Inactive - Terrastra)"] = GetSpellInfo(92067),
    ["[Council] CD - [Phase 2] Harden Skin (Terrastra)"]                = "Shield",
    ["[Council] CD - [Phase 2] Gravity Well (Terrastra)"]               = GetSpellInfo(83578),
    ["[Council] CD - [Phase 2] Call Winds (Arion)"]                     = GetSpellInfo(83491),
    ["[Council] CD - [Phase 2] Flame Strike (Inactive - Ignacious)"]    = "Flame Circles",
    ["[Council] CD - [Phase 3] Gravity Crush"]                          = GetSpellInfo(84948),
    ["[Council] CD - [Phase 3] Lava Seed"]                              = GetSpellInfo(84913),
    ["[T&V] CD - Next Swap"]                                            = "Boss Switch",
    ["[T&V] CD - Twilight Shift [Tank]"]                                = GetSpellInfo(93051),
    ["[T&V] CD - Devouring Flames (Valiona @Ground)"]                   = "Frontal",
    ["[T&V] CD - Blackout (Valiona @Ground)"]                           = "Raid Stack",
    ["[T&V] CD - Dazzling Destruction (Theralion @Air)"]                = "Swirling circles",
    ["[T&V] CD - Fabulous Flames (Theralion @Ground)"]                  = GetSpellInfo(86505),
    ["[T&V] CD - Engulfing Magic (Theralion @Ground)"]                  = "Spread Debuff",
    ["[T&V] CD - Deep Breath (Valiona @Air)"]                           = GetSpellInfo(86059),
    ["[Halifus] CD - Breath"]                                           = "Raid Damage",
    ["[Halifus] CD - Shadow Nova"]                                      = "Knockback",
    ["[Halifus] CD - Furious Roar"]                                     = "Triple Stun",
    ["[Halifus] CD - Paralysis"]                                        = "Boss Paralyzed",
    
    -- Bastion [Circled Textures]
    ["[Sinestra] Circled Texture_01"] = "Orbs Soon",
    ["[Sinestra] Circled Texture_02"] = "Switch to Eggs",
    ["[Chogall] Circled Texture_01"]  = "Big Adds Soon",
    ["[Chogall] Circled Texture_02"]  = "Prepare to Face Away",
    ["[Chogall] Circled Texture_03"]  = "FACE AWAY",
    ["[Council] Circled Texture_01"]  = "Gravity Crush",
    ["[Council] Circled Texture_02"]  = "Phase 3 Soon",
    ["[T&V] Circled Texture_01"]      = "Frontal Soon",
    ["[T&V] Circled Texture_02"]      = "Watch Valiona for Breath",
    ["[Halfus] Circled Texture_01"]   = "Boss Stunned Soon",
    ["[Halfus] Circled Texture_02"]   = "Burst Boss",
    
    -- Bastion [Warnings]
    ["[Sinestra] W - Phase 3"]                                     = "Phase",
    ["[Sinestra] W - Phase 2"]                                     = "Phase",
    ["[Sinestra] W - Phase 2 Soon"]                                = "Phasing in",
    ["[Sinestra] Whelps"]                                          = "Summon Whelps",
    ["[Chogall] W - Phase 2"]                                      = "Phase",
    ["[Chogall] W - 85% Soon"]                                     = "Big Add in",
    ["[Chogall] Warning - [Phase 1] Spilled Blood"]                = "Oozes Spawn",
    ["[Chogall] Warning - [Phase 1] Interrupt Worship"]            = "Interrupt Worships! ",
    ["[Chogall] Warning - [Phase 1] Fire Elemental Portal"]        = "Fire Elemental Spawned ",
    ["[Chogall] Warning - [Phase 1] Shadow Elemental Portal"]      = "Shadow Elemental Spawned",
    ["[Council] Warning - Static Overload"]                         = GetSpellInfo(92067),
    ["[Council] Warning - Gravity Core"]                            = GetSpellInfo(92075),
    ["[Council] Warning - Heart of Ice"]                            = GetSpellInfo(82665),
    ["[Council] Warning - Frost Beacon"]                            = "Frozen Orb",
    ["[Council] W - Phase 3"]                                      = "Phase",
    ["[Council] W - Phase 2"]                                      = "Phase",
    ["[T&V] W - Twilight Shift [Tank]"]                            = GetSpellInfo(93051),
    ["[T&V] W - Dazzling Destruction"]                             = "Watch your feet",
    ["[T&V] SW - Deep Breath"]                                     = GetSpellInfo(86059),
    ["[T&V] W - Valiona Landed"]                                   = "Valiona is Landing",
    ["[T&V] W - Theralion Landed"]                                 = "Theralion is Landing",
    
    -- Bastion [Special Warnings]
    ["[Sinestra] SW - Egg Shield"]                      = "EGG SHIELD",
    ["[Sinestra] SW - Eggs Weaken"]                     = "SWITCH ON EGGS",
    ["[Sinestra] SW - GTFO"]                            = "GTFO",
    ["[Sinestra] SW - Flame Breath"]                    = string.upper(GetSpellInfo(90125)),
    ["[Chogall] SW - GTFO: Blaze"]                      = "GTFO",
    ["[Chogall] SW - GTFO: Spilled Blood"]              = "GTFO",
    ["[Chogall] SW - Adherent Spawn"]                   = "BIG ADDS",
    ["[Chogall] SW - Corrupting Crash on You"]          = "CRASH ON YOU! RUN OUT!",
    ["[Chogall] SW - Corrupting Crash Near"]            = "CRASH NEAR",
    ["[Council] SW - Glaciate"]                         = "RAID DAMAGE",
    ["[Council] SW - Aegis of Flame"]                   = string.upper(GetSpellInfo(82631)),
    ["[Council] SW - Dodge Water Bomb"]                 = "DODGE BOMBS!",
    ["[Council] SW - Dodge Lava Seeds"]                 = "DODGE LAVA SEEDS",
    ["[Council] SW - Glaciate Range Check_01"]          = "RANGE CHECK ON GLACIATE",
    ["[Council] SW - Glaciate Range Check_02"]          = "GET AWAY FROM FELUDIUS",
    ["[Council] SW - Glaciate Range Check_03"]          = "YOU`RE FINE BRUV",
    ["[Council] SW - GTFO"]                             = "GTFO",
    ["[T&V] SW - GTFO"]                                 = "GTFO",
    ["[T&V] SW - Twilight Zone"]                        = string.upper(GetSpellInfo(86214)),
    ["[T&V] SW - Wrong Target_01"]                      = "SWITCH TARGET TO",
    ["[T&V] SW - Wrong Target_02"]                      = "VALIONA",
    ["[T&V] SW - Blackout"]                             = "STACK!",
    ["[T&V] SW - Fabulous Flames On You"]               = "FLAMES ON YOU! RUN OUT!",
    ["[T&V] SW - Devouring Flames"]                     = "DODGE FRONTAL",
    ["[Halifus] SW - Furious Roar"]                     = "TRIPLE STUN",
    
    -- Bastion [@Nameplates]
    ["[Sinestra] Face Away"]                              = "Casting Frontal",
    ["[Sinestra] Stop the Cast!"]                         = "Stop the Cast!",
    ["[Chogall] Targetted by Ooze"]                       = "Chasing You",
    ["[Chogall] Mind Controlled"]                         = "Interrupt",
    ["[Chogall] Depravity (Adherent Cast)"]               = "Interrupt",
    ["[Council] SW - Interrupt Rising Flames"]            = "Interrupt",
    ["[Council] SW - Interrupt Harden Skin"]              = "Interrupt",
    ["[Trash] Focus Mob (Portal) @Nameplate"]             = "Interrupt",
    ["[Trash] I hate this cast please do something"]      = "",
    ["[Sinestra] Indomitable Enrage_01"]                  = "Dispel",
    ["[Sinestra] Indomitable Enrage_02"]                  = "Enraged",
    
    -- Bastion [@Nameplates Cooldowns]
    ["[Trash] @Nameplate Cooldowns"]                       = "",
    ["[Sinestra] @Nameplate - Twilight Breath CD"]         = "Frontal",
    ["[Council] @Nameplate - Flame Torrent CD"]            = "Frontal",
    ["[Halfus] @Nameplate - Shadow Nova CD"]               = "Knock",
    ["[Council] @Nameplate - Inferno Leap CD"]             = "Leap",
    ["[Council] @Nameplate - Hydro Lance CD"]              = "Frontal",
    ["[Council] @Nameplate - Eruption CD"]                 = "Spikes",
    ["[Council] @Nameplate - Disperse CD"]                 = "Teleport",
    
    -- Bastion [Lists [RL/Assist]]
    ["[Council] Frost Imbued - Counter"]     = "+Damage On Fire",
    ["[Council] Flame Imbued - Counter"]     = "+Damage On Frost",

    -- Bastion [Alternative Widgets]
    ["[Council] Quake_01"]                   = GetSpellInfo(83565),
    ["[Council] Quake_02"]                   = "Get Winds!",
    ["[Council] Thundershock_01"]            = GetSpellInfo(83067),
    ["[Council] Thundershock_02"]            = "Get Grounded!",
}

addonTable.localization.chat['enUS'] = {
}