local _, addonTable = ...

local GetSpellInfo = GetSpellInfo
local stformat = string.format

local mainPath = 'Interface\\AddOns\\MerfinPlus\\sound\\ruRU\\'
local GetSoundPath = function(folderName, soundFileName)
    return stformat('%s%s\\%s', mainPath, folderName, soundFileName)
end

local General = {
    ["GTFO"] = 'Сваливай',
}

addonTable.localization.msg['ruRU'] = {
    -- [CataRaid_BWD] Icons
    ["[Nefarian] Stolen Power Buff"]                = "урон/хил",
    ["[Nefarian] Free Your Mind Buff"]              = "+120%\nскорость",
    ["[Nefarian] Shadow of Cowardice Debuff"]       = "Урон Тьмы\n по Тебе",
    ["[Maloriak] Dark Sludge Debuff"]               = "Сваливай",
    ["[Maloriak] Engulfing Darkness Debuff"]        = "-100%\nвход. хила",
    ["[Maloriak] Steal Remedy"]                     = "Спэлстиль\nХотку с Босса",
    ["[Atramedes] Pestered!"]                       = "Цель\nИмпа",
    ["[Atramedes] Searing Flame"]                   = "Урон\nпо Тебе",
    ["[Atramedes] Roaring Flame Debuff"]            = "Огонь ДоТ",
    ["[Chimaeron] Caustic Slime"]                   = "-75% хита",
    ["[Chimaeron] Missing Finkle's Mixture Debuff"] = "Нет Иммуна\nк Ваншоту",
    ["[Chimaeron] Mocking Shadows (2nd phase)"]     = "2к Урона\nв Сек",
    ["[Chimaeron] Mortality (2nd phase)"]           = "Хиль",
    ["[ODS] Power Generator Debuff"]                = "Урон",
    ["[ODS] Power Generator Missing [DPS]"]         = "Забеги в\nСинюю Лужу",
    ["[ODS] Steal Converted Power"]                 = "Спэлстиль",
    ["[ODS] Chemical Cloud Debuff"]                 = "повышен\nурон\nпо тебе",
    ["[ODS] Soaked in Poison Debuff"]               = "Сдиспель\nЯд",
    ["[Magmaw] Parasitic Infection Debuff"]         = "Паразит\nна Тебе",
    ["[Trash] Debuff - Magma (BWD)"]                = "Урон\nпо Тебе",
    ["[Trash] Debuff - Flame Buffet_1"]             = "Огонь ДоТ",
    ["[Trash] Debuff - Flame Buffet_2"]             = "Урон\nпо Тебе",
    ["[Trash] Debuff - Shadowflame"]                = "Тьма ДоТ",
    ["[Trash] Debuff - Flash Bomb"]                 = "Оглушен",
    ["[Trash] Debuff - Burden of the Crown_1"]      = "Обратка\nНе убейся",
    ["[Trash] Debuff - Burden of the Crown_2"]      = '+Урон',

    -- [CataRaid_BWD] Big Icons
    ["[Nefarian] Debuff - Explosive Cinders"]       = "Будь Готов\nВыбегать",
    ["[Nefarian] Debuff - Dominion"]                = "Майнд Контроль",
    ["[Maloriak] Debuff - Flash Freeze"]            = "Заморожен",
    ["[Maloriak] Debuff - Biting Chill"]            = "Разойдись",
    ["[Maloriak] Debuff - Consuming Flames"]        = "Сваливай",
    ["[Artamedes] Debuff - Tracking"]               = "Слежка",
    ["[Artamedes] Debuff - Boss Stun"]              = "Босс в Стане",
    ["[Atramedes] Noisy"]                           = "Понизь\nШум!",
    ["[ODS] Overcharged Power Generator Debuff_1"]  = "Выбеги\nиз Лужи",
    ["[ODS] Overcharged Power Generator Debuff_2"]  = "+100% урона",
    ["[ODS] Debuff - Shadow Infusion"]              = "Приготовься\nзастакаться",
    ["[ODS] Debuff - Shadow Conductor"]             = "Встань\nв Рейд",
    ["[ODS] Debuff - Lightning Conductor"]          = "Сваливай",
    ["[ODS] Debuff - Encasing Shadow"]              = "Обездвижен",
    ["[ODS] Debuff - Acquiring Target"]             = "Уйди от\nЛица Босса",
    ["[ODS] Debuff - Fixated"]                      = "Слизни\nна Тебе",
    ["[Magmaw] Debuff - Mangle"]                    = "Схвачен",
    ["[Magmaw] Debuff - Shadow Breath"]             = "НЕ подходи",
    ["[Trash] Debuff - Piercing Grip"]              = "Схвачен",
    ["[Trash] Debuff - Aura of Dead"]               = "НЕ подходи",

    -- [CataRaid_BWD] Progress Bars
    ["[Nefarian] Nefarian Roleplay"]                = "Возрождение Ониксии",
    ["[Nefarian] Nefarian Landing"]                 = "Приземление Нефариана",
    ["[Nefarian] Electrocute"]                      = "Рейдовый Урон", -- TODO
    ["[Maloriak] Debilitating Slime"]               = "Повышенный урон",
    ["[Maloriak] Engulfing Darkness_1"]             = "Можно Хилить",
    ["[Maloriak] Engulfing Darkness_2"]             = "-100% к хилу перед собой",
    ["[Maloriak] Arcane Storm"]                     = "Урон по Рейду",
    ["[Maloriak] Release Abberation"]               = "Появление Аберраций",
    ["[Atramedes] Air Phase Duration"]              = "Воздушная Фаза",
    ["[Atramedes] Searing Flames"]                  = "Большой урон по рейду",
    ["[Chimaeron] Reroute Power"]                   = "Деактивация Робота",
    ["[Chimaeron] Fight Start"]                     = "Начало Боя",
    ["[ODS] Shadow Infusion"]                       = "Стакнись на",
    ["[ODS] Incineration Security Measure"]         = "Урон по Рейду",
    ["[ODS] Poison Protocol"]                       = "Появление Слизней",
    ["[Magmaw] Lava Spew [Healer]"]                 = "Урон по Рейду",
    ["[Magmaw] Armageddon Cast"]                    = "Уйди от Большого Адда",
    ["[Magmaw] Head Exposed"]                       = "БУРСТИ БОССА",
    ["[Magmaw] Molten Tantrum Buff"]                = "увеличен урон босса",
    ["[Trash] Shadowflame Cast"]                    = "Избегай Фронтал",
    ["[Trash] Sacrifice Debuff"]                    = "Cбей каст",
    ["[Trash] Whirlwind Cast"]                      = "Избегай Вихрь",

    -- [CataRaid_BWD] Alternative Powers
    ["[Atramedes] Alternative Power - Loud"]        = 'Шум',
    ["[Maloriak] Counter - Abberations_1"]          = 'Темная Фаза',
    ["[Maloriak] Counter - Abberations_2"]          = 'Синяя Фаза',
    ["[Maloriak] Counter - Abberations_3"]          = 'Красная Фаза',
    ["[Maloriak] Counter - Abberations_4"]          = 'Зеленая Фаза',

    -- [CataRaid_BWD] Little Progress Bars
    ["[Nefarian] Shadowblaze Spark PreWarning"]     = GetSpellInfo(81031),

    -- [CataRaid_BWD] Cooldowns
    ["[Nefarian] CD - Shadowblaze Spark"]           = GetSpellInfo(81031),
    ["[Nefarian] CD - Explosive Cinders"]           = GetSpellInfo(79339),
    ["[Nefarian] CD - Dominion"]                    = 'Майнд Контроль',
    ["[Nefarian] CD - Lightning Discharge"]         = GetSpellInfo(77939),
    ["[Nefarian] CD - Shadowflame Breath [Tank]"]   = 'Дыхание',
    ["[Nefarian] CD - Tail Lash [Tank]"]            = GetSpellInfo(77827),
    ["[Maloriak] Next Phase Dark (Heroic)"]         = 'Темная Фаза',
    ["[Maloriak] Next Phase Blue or Red"]           = 'Синяя/Красная Фаза',
    ["[Maloriak] Next Phase Blue"]                  = 'Синяя Фаза',
    ["[Maloriak] Next Phase Red"]                   = 'Красная Фаза',
    ["[Maloriak] Next Phase Green"]                 = 'Зеленая Фаза',
    ["[Maloriak] CD - Arcane Storm"]                = GetSpellInfo(77896),
    ["[Maloriak] CD - Release Abberation"]          = GetSpellInfo(77569),
    ["[Maloriak] CD - Flash Freeze"]                = GetSpellInfo(77699),
    ["[Maloriak] CD - Debilitating Slime"]          = '+Урон по Врагам',
    ["[Maloriak] CD - Scorching Blast"]             = 'Урон по Рейду',
    ["[Maloriak] CD - Consuming Flames"]            = GetSpellInfo(77786),
    ["[Maloriak] CD - Magma Jets"]                  = 'Избегай Фронтал',
    ["[Maloriak] CD - Absolute Zero"]               = 'Ледяные Сферы',
    ["[Maloriak] CD - Engulfing Darkness"]          = 'Фронтал',
    ["[Atramedes] CD - Air Phase"]                  = 'Воздушная Фаза',
    ["[Atramedes] CD - Searing Flames"]             = 'Большой урон по рейду',
    ["[Atramedes] CD - Sonic Breath"]               = 'Фронтал',
    ["[Atramedes] CD - Modulation"]                 = 'Урон по Рейду',
    ["[Atramedes] CD - Sonar Pulse"]                = 'Плохие Кругляши',
    ["[Chimaeron] CD - Massacre"]                   = 'Падение Здоровья',
    ["[Chimaeron] CD - Systems Failure"]            = GetSpellInfo(88853),
    ["[Chimaeron] CD - Break [Tank]"]               = GetSpellInfo(82881),
    ["[Chimaeron] CD - Caustic Slime"]              = GetSpellInfo(82935),
    ["[ODS] CD - Next Activation"]                  = 'Следующая Активация',
    ["[ODS] CD - Nefarian Special Ability"]         = 'Усиление Нефариана',
    ["[ODS] CD - Power Generator (Arcanotron)"]     = 'Лужа на +Урон',
    ["[ODS] CD - Lightning Conductor (Electron)"]   = GetSpellInfo(79888),
    ["[ODS] CD - Chemical Bomb (Toxitron)"]         = GetSpellInfo(80157),
    ["[ODS] CD - Poison Protocol (Toxitron)"]       = 'Появились Слизни',
    ["[ODS] CD - Incineration Security Measure (Magmatron)"] = 'Урон по Рейду',
    ["[ODS] CD - Acquiring Target (Magmatron)"]     = 'Фронтал',
    ["[Magmaw] CD - Pillar of Flame"]               = GetSpellInfo(78006),
    ["[Magmaw] CD - Inferno"]                       = 'Большой Адд',
    ["[Magmaw] CD - Lava Spew"]                     = 'Урон по Рейду',
    ["[Magmaw] CD - Mangle"]                        = GetSpellInfo(89773),
    ["[Trash] CD - Chain Lightning"]                = GetSpellInfo(80646),
    ["[Trash] CD - Drakonid Rush"]                  = GetSpellInfo(79630),
    ["[Trash] CD - Enrage"]                         = GetSpellInfo(80084),
    ["[Trash] CD - Piercing Grip"]                  = GetSpellInfo(80145),
    ["[Trash] CD - Shadowflame"]                    = GetSpellInfo(79921),
    ["[Trash] CD - Laser Strike"]                   = GetSpellInfo(81063),
    ["[Trash] CD - Flash Bomb"]                     = GetSpellInfo(81056),

    -- [CataRaid_BWD] Warnings
    ["[Nefarian] W - Phase 2"]                      = 'Фаза',
    ["[Nefarian] W - Phase 3"]                      = 'Фаза',
    ["[Nefarian] W - Explosive Cinders"]            = GetSpellInfo(79339),
    ["[Nefarian] W - Dominion"]                     = 'Майнд Контроль',
    ["[Maloriak] W - Absolute Zero"]                = 'Появились Сферы',
    ["[Maloriak] W - Consuming Flames"]             = GetSpellInfo(77786),
    ["[Maloriak] W - Phase 2"]                      = 'Фаза',
    ["[Maloriak] W - Phase 2 Soon"]                 = 'Фаза',
    ["[Maloriak] W - Red Phase"]                    = 'Красная Фаза',
    ["[Maloriak] W - Blue Phase"]                   = 'Синяя Фаза',
    ["[Maloriak] W - Green Phase"]                  = 'Зеленая Фаза',
    ["[Maloriak] W - Dark Phase"]                   = 'Темная Фаза',
    ["[Atramedes] W - Shield Used By"]              = 'Задействован Щит',
    ["[Atramedes] W - Tracking"]                    = GetSpellInfo(78092),
    ["[Atramedes] W - Air Phase"]                   = 'Воздушная Фаза',
    ["[Chimaeron] W - Phase 2"]                     = 'Фаза',
    ["[Chimearon] W - Phase 2 Soon"]                = 'Фаза',
    ["[Chimaeron] W - Break [Tank]"]                = GetSpellInfo(82881),
    ["[Chimaeron] W - Double Attack [Tank]"]        = GetSpellInfo(88826),
    ["[ODS] W - Boss Activated"]                    = 'Активирован',
    ["[ODS] W - Acquiring Target"]                  = 'Фронтал на',
    ["[ODS] W - Lightning Conductor"]               = 'Отбеги от',
    ["[ODS] W - Power Generator"]                   = 'Стой в Синей Луже',
    ["[Trash] W - Laser Strike"]                    = 'Не стой в Войд Зоне',
    ["[Trash] W - Flash Bomb"]                      = 'Не стой в Войд Зоне',
    ["[Trash] W - Enrage"]                          = GetSpellInfo(80084),
    ["[Trash] W - Sacrifice"]                       = 'Казнь на',

    -- [CataRaid_BWD] Special Warnings
    ["[Nefarian] GTFO - Shadowblaze"]               = "СВАЛИВАЙ",
    ["[Nefarian] Shadowblaze Spark"]                = GetSpellInfo(81031),
    ["[Maloriak] GTFO - Dark Sludge"]               = "СВАЛИВАЙ",
    ["[Maloriak] SW - Remedy Dispel"]               = "ДИСПЕЛЬ",
    ["[Atramedes] SW - Sonic Breath"]               = GetSpellInfo(78075),
    ["[Atramedes] SW - Searing Flames"]             = GetSpellInfo(77840),
    ["[Atramedes] SW - Sonar Pulse"]                = "ИЗБЕГАЙ КОЛЬЦА",
    ["[Atramedes] SW - Switch on Imp"]              = "ПЕРЕКЛЮЧИСЬ В ИМПА",
    ["[Chimaeron] SW - Systems Failure"]            = GetSpellInfo(88853),
    ["[Chimaeron] SW - Double Attack [Tank]"]       = GetSpellInfo(88826),
    ["[ODS] SW - GTFO"]                             = "СВАЛИВАЙ",
    ["[ODS] SW - Stop Attacking"]                   = "НЕ БЕЙ",
    ["[ODS] SW - Power Generator @ Boss [Tank]"]    = "ПОДВИНЬ БОССА",
    ["[Magmaw] SW - Jump Now"]                      = "ПРЫГАЙ СЕЙЧАС",
    ["[Magmaw] SW - Jump on Head Countdown"]        = "ПРЫГАЙ НА ГОЛОВУ",
    ["[Magmaw] SW - Pillar of Flame"]               = "СМОТРИ ПОД НОГИ! ЧЕРВИ!",
    ["[Magmaw] SW - Inferno"]                       = "БОЛЬШОЙ АДД",
    ["[Magmaw] SW - GTFO: Ignition"]                = "СВАЛИВАЙ",
    ["[Trash] GTFO - Flame Breath"]                 = "СВАЛИВАЙ",
    ["[Trash] GTFO - Laser Strike"]                 = "СВАЛИВАЙ",
    ["[Trash] GTFO - Flash Bomb"]                   = "СВАЛИВАЙ",

    -- [CataRaid_BWD] Circled Textures
    ["[Nefarian] Circled Texture"]                  = "Скоро Контроль",
    ["[Maloriak] Circled Texture_1"]                = "Темная Фаза Скоро",
    ["[Maloriak] Circled Texture_2"]                = "Синяя / Красная Фаза Скоро",
    ["[Maloriak] Circled Texture_3"]                = "Синяя Фаза Скоро\nГотовься Разбежаться!",
    ["[Maloriak] Circled Texture_4"]                = "Красная Фаза Скоро\nГотовься Стакаться!",
    ["[Maloriak] Circled Texture_5"]                = "Зеленая Фаза Скоро",
    ["[Maloriak] Circled Texture_6"]                = "Увернись от Фронталки",
    ["[Chimaeron] Circled Texture_1"]               = "Скоро Упадет Здоровье",
    ["[Chimaeron] Circled Texture_2"]               = "Падение Здоровья",
    ["[Chimaeron] Circled Texture_3"]               = "Начало Боя",
    ["[Atramedes] Circled Texture_1"]               = "Скоро Фронтал",
    ["[Atramedes] Circled Texture_2"]               = "Наземная Фаза",
    ["[ODS] Circled Texture_1"]                     = "Мертвая Хватка",
    ["[ODS] Circled Texture_2"]                     = "Взрыв! Убегай!",
    ["[Magmaw] Circled Texture"]                    = "Скоро Столб Пламени", --TODO
    ["[Trash] Circled Texture"]                     = "Скоро Фронтал",

    -- [CataRaid_BWD] @Nameplates
    ["[Magmaw] Nameplate Text - Targetted by Worm"] = "Преследует тебя",

    -- [CataRaid_T4W] Icon
    ["[Al'Akir] Debuff - Acid Raid"]                              = "урона\nв сек",
    ["[Al'Akir] Buff - Eye of the Storm"]                         = "скорость",
    ["[Conclave] Debuff - Hurricane"]                             = "+хаста",
    ["[Conclave] Debuff - Ice Path"]                              = "Выбеги",
    ["[Conclave] Debuff - [Anshal] Toxic Spores"]                 = "ДоТ",
    ["[Conclave] Debuff - [Anshal] Withering Winds (Alone)_1"]    = "-100% к хилу",
    ["[Conclave] Debuff - [Anshal] Withering Winds (Alone)_2"]    = "Аншал",
    ["[Conclave] Debuff - [Rohash] Deafing Winds (Alone)_1"]      = "Безмолвие",
    ["[Conclave] Debuff - [Rohash] Deafing Winds (Alone)_2"]      = "Рохаш",
    ["[Conclave] Debuff - [Nezir] Chilling Winds (Alone)_1"]      = "-500% к хасте",
    ["[Conclave] Debuff - [Nezir] Chilling Winds (Alone)_2"]      = "Незир",
    ["[T4W] Debuff - Jet Stream"]                                 = "КД Перелета",

    -- [CataRaid_T4W] Big Icons
    ["[Al'Akir] Debuff - Lightning Rod"]        = "Улетай!",
    ["[Al'Akir] Debuff - Ice Storm"]            = "Отбеги",
    ["[Al'Akir] Debuff - Electrocute"]          = "Беги к\nМили",
    ["[Al'Akir] Debuff - Squall Line"]          = "Избегай Ветерков",
    ["[Conclave] Debuff - Soothing Breeze"]     = "Выбеги",

    -- [CataRaid_T4W] Progress Bars
    ["[Al'Akir] Lightning Rod"]                = "АоЕ урон",
    ["[Al'Akir] Feedback"]                     = "Урон по Боссу",
    ["[Conclave] Special"]                     = "Особая Способность",
    ["[Conclave] [Rohash] Wind Blast"]         = GetSpellInfo(86193),

    -- [CataRaid_T4W] Little Progress Bars
    ["[Conclave] Anfall Revive"]         = "Возрождение Аншал",
    ["[Conclave] Nezir Revive"]          = "Возрождение Незир",
    ["[Conclave] Rohash Revive"]         = "Возрождение Рохаша",
    ["[Al'Akir] Next Acid Rain"]         = GetSpellInfo(88301),

    -- [CataRaid_T4W] Cooldowns
    ["[Al'Akir] CD - Ice Storm"]                         = "Ледяная Буря",
    ["[Al'Akir] CD - Wind Burst"]                        = "Откидывание",
    ["[Al'Akir] CD - Squad Line"]                        = "Торнадо",
    ["[Al'Akir] CD - Stormling"]                         = "Адд",
    ["[Al'Akir] CD - Lightning Clouds"]                  = GetSpellInfo(89588),
    ["[Al'Akir] CD - Lightning Rod"]                     = "Дебафф (Улетай)",
    ["[Conclave] CD - Special"]                          = "Особая Способность",
    ["[Conclave] CD - [Anshal] Soothing Breeze"]         = "Зеленые Круги",
    ["[Conclave] CD - [Anshal] Nurture"]                 = "Маленькие Адды",
    ["[Conclave] CD - [Anshal] Toxic Spores"]            = GetSpellInfo(86281),
    ["[Conclave] CD - [Nezir] Wind Chill"]               = "Урон по Рейду",
    ["[Conclave] CD - [Nezir] Ice Patch"]                = GetSpellInfo(86111),
    ["[Conclave] CD - [Nezir] Perma Frost"]              = "Фронталка в Цель",
    ["[Conclave] CD - Wind Blast"]                       = GetSpellInfo(86193),
    ["[Conclave] CD - Storm Shield"]                     = GetSpellInfo(93059),

    -- [CataRaid_T4W] Circled Textures
    ["[Conclave] Circled Texture_1"]                     = "Зайди за босса!",
    ["[Conclave] Circled Texture_2"]                     = "Особая Способность Скоро",
    ["[Al'Akir] Circled Texture_1"]                      = "Откидывание",
    ["[Al'Akir] Circled Texture_2"]                      = GetSpellInfo(89588),

    -- [CataRaid_T4W] Warnings
    ["[Al'Akir] W - Phase 3"]                            = "Фаза",
    ["[Al'Akir] W - Phase 2"]                            = "Фаза",
    ["[Al'Akir] W - Phase 2 Soon"]                       = "Фаза",
    ["[Al'Akir] W - Phase 3 Soon"]                       = "Фаза",
    ["[Al'Akir] W - [Phase 1] Ice Storm"]                = "Смотри за Ледяной Бурей!",
    ["[Al'Akir] W - [Phase 1/2] Squad Line"]             = "Смотри за Торнадо!",
    ["[Al'Akir] W - [Phase 2] Stormling"]                = "Появились Адды",
    ["[Al'Akir] W - [Phase 2] Feedback"]                 = "Урон по Боссу",
    ["[Al'Akir] W - [Phase 3] Lightning Rod"]            = GetSpellInfo(89668),
    ["[Conclave] W - [Anshal] Nurture"]                  = "Маленькие Адды",
    ["[Conclave] W - [Nezir] Ice Patch"]                 = "Не стой на Льду",
    ["[Conclave] W - [Anshall] Toxic Spores"]            = GetSpellInfo(86281),

    -- [CataRaid_T4W] Special Warnings
    ["[Al'Akir] SW - [Phase 3] Short Distance"]           = "КОРОТКИЙ ПЕРЕЛЕТ",
    ["[Al'Akir] SW - [Phase 3] Long Distance"]            = "ДЛИННЫЙ ПЕРЕЛЕТ",
    ["[Al'Akir] SW - Wind Burst"]                         = GetSpellInfo(87770),
    ["[Al'Akir] SW - GTFO [Lightning Clouds]"]            = "СВАЛИВАЙ",
    ["[Al'Akir] SW - GTFO [Ice Storm]"]                   = "СВАЛИВАЙ",
    ["[Al'Akir] SW - Lightning Rod_1"]                    = GetSpellInfo(89668),
    ["[Al'Akir] SW - Lightning Rod_2"]                    = "На Тебе",
    ["[Conclave] SW - GTFO"]                              = "СВАЛИВАЙ",
    ["[Conclave] SW - [Rohash] Storm Shield"]             = GetSpellInfo(93059),
    ["[Conclave] SW - [Rohash] Summon Tornados"]          = "СМОТРИ ЗА ТОРНАДО!",
    ["[Conclave] SW - [Rohash] Wind Blast"]               = "НЕ СТОЙ ПЕРЕД БОССОМ",
    ["[Conclave] SW - [Anshal] Move Boss"]                = "БОСС ВНУТРИ КРУГА",

    -- CataRaid_Bastion [Icons]
    ["[Sinestra] Buff - Fiery Barrier_01"]                  = "Нет\nЩита",
    ["[Sinestra] Buff - Fiery Barrier_02"]                  = "-99%\nУрона\nТьмы",
    ["[Sinestra] Buff - Essence of the Red"]                = "+100% скорости",
    ["[Chogal] Debuff - [Phase 2] Debilitating Beam_01"]    = "-75% хила\n-75% урона",
    ["[Chogal] Debuff - [Phase 2] Debilitating Beam_02"]    = "Глаза на тебе",
    ["[Council] Debuff - [Phase 1] Water Bomb_01"]          = "-25% скорости",
    ["[Council] Debuff - [Phase 1] Water Bomb_02"]          = "Сними\nв огне",
    ["[Council] Debuff - [Phase 1] Heart of Ice"]           = "Милишники!",
    ["[Council] Debuff - [Phase 1] Burning Blood"]          = "Кастеры!",
    ["[Council] Buff - [Phase 1] Frost Imbued"]             = "+Урон по\nОгненному",
    ["[Council] Buff - [Phase 1] Flame Imbued"]             = "+Урон по\nЛедяному",
    ["[Council] Debuff - [Phase 2] Magnetic Pull"]          = "-50%\nскорости",
    ["[Council] Debuff - [Phase 3] Gravity Crush"]          = "Оглушен",
    ["[T&V] Twilight Zone Debuff"]                          = "+ Урон\nот магии Тьмы",
    ["[Halfus] Furious Roar Debuff"]                        = "Оглушен",
    ["[Trash] Debuff - Shockwave"]                          = "Оглушен",
    ["[Trash] Debuff - Entomb"]                             = "Expose to\nWinds",
    ["[Trash] Debuff - Rending Gale"]                       = "Expose to\nEarth",
    ["[Trash] Debuff - Dark Pool"]                          = "Не стой\nв луже",
    ["[Trash] Debuff - Vaporize"]                           = "-100%\nармора",
    ["[Trash] Debuff - Cold-Touched"]                       = "Иммунитет\nк урону огня",
    ["[Trash] Debuff - Tremors"]                            = "Выбегай",
    ["[Trash] Debuff - Stasis Strike"]                      = "Оглушен",
    ["[Trash] Debuff - Soul Blade"]                         = "ДоТ",
    ["[Trash] Debuff - Phased Burn"]                        = "Урон от\nКолодца",
    ["[Trash] Debuff - Magma [Bastion]"]                    = "Урон\nпо Тебе",

    -- CataRaid_Bastion [Big Icons]
    ["[Sinestra] Orb Chasing You"]                      = "Сфера на Тебе?",
    ["[Sinestra] Debuff - Wrack"]                       = "Смятие - Урон",
    ["[Chogal] Debuff - Worshipping"]                   = "Под контролем\nразума",
    ["[Chogal] Debuff - Corruption Absolute"]           = "+100% урона\n-100% хила",
    ["[Chogal] Debuff - Corruption Malformation"]       = "Разойдись",
    ["[Chogal] Debuff - Corruption Accelerated"]        = "Диспел\nСРОЧНО",
    ["[Council] Debuff - [Phase 1] Static Overload_01"] = "Разойдись",
    ["[Council] Debuff - [Phase 1] Static Overload_02"] = "Беги к {rt2}",
    ["[Council] Debuff - [Phase 1] Gravity Core_01"]    = "Разойдись",
    ["[Council] Debuff - [Phase 1] Gravity Core_02"]    = "Беги к {rt6}",
    ["[Council] Debuff - [Phase 2] Lightning Rod_01"]   = GetSpellInfo(83099),
    ["[Council] Debuff - [Phase 2] Lightning Rod_02"]   = "Выбеги",
    ["[Council] Debuff - [Phase 2] Lightning Rod_03"]   = "Можно вбегать\nобратно",
    ["[Council] Debuff - [Phase 2] Frost Beacon"]       = "Заведи Сферу\nна огонь!",
    ["[Council] Debuff - Frozen"]                       = "Заморожен",
    ["[T&V] Debuff - Blackout"]                         = "Сбегись с\nрейдом!",
    ["[T&V] Debuff - Meteor"]                           = "Сбегись с\nрейдом!",
    ["[T&V] Debuff - Exploding"]                        = "Разойдись\nили\nпрекрати кастить",

    -- CataRaid_Bastion [Alternative Power]
    ["[Chogal] Corruption Blood (Alternate Power)"]     = "Порча крови",
    ["[Sinestra] [Phase 2] Calen - Health"]             = "Здоровье Кален",
    ["[Sinestra] [Phase 2] Sinestra Mana Barrier"]      = "Мана Синестры",

    -- CataRaid_Bastion [Progress Bars]
    ["[Sinestra] Shadow Orbs Duration"]                 = "Темные Шары",
    ["[Sinestra] Twilight Extinction Duration"]         = "-99% урона по боссу",
    ["[Sinestra] Mana Barrier"]                         = "Щит маны",
    ["[Chogal] Empowered Shadows Buff (Healers)"]       = "Урон по Рейду",
    ["[Chogal] Flaming Destruction"]                    = "Огненные атаки",
    ["[Chogal] Phasing"]                                = "Фазирование",
    ["[Council] Glaciate Cast"]                         = "Большой урон по рейду",
    ["[Council] Gravity Crush"]                         = GetSpellInfo(84948),
    ["[T&V] Blackout Duration"]                         = "Раздели урон",
    ["[T&V] Devouring Flames Cast"]                     = "Зайди за босса!",
    ["[Halifus] Scorching Breath Duration_01"]          = "Урон по Рейду",
    ["[Halifus] Scorching Breath Duration_02"]          = GetSpellInfo(83855),
    ["[Halifus] Furious Roar"]                          = "Оглушения",
    ["[Halifus] Fireball Barrage"]                      = GetSpellInfo(83706),

    -- CataRaid_Bastion [Little Progress Bars]
    ["[Sinestra] Egg Weaken Duration"]                  = "Яйца Ослаблены",
    ["[Halfus] Scorching Breath Incoming [Healer]"]     = GetSpellInfo(83855),

    -- CataRaid_Bastion [Cooldowns]
    ["[Sinestra] CD - [Phase 1] Whelps"]                                = "Дракончики",
    ["[Sinestra] CD - [Phase 1] Flame Breath"]                          = GetSpellInfo(90125),
    ["[Sinestra] CD - [Phase 1] Shadow Orbs"]                           = "Темные Шары",
    ["[Chogal] CD - [Phase 1] Worship"]                                 = "Майнд Контроль",
    ["[Chogal] CD - [Phase 1] Flame Orders_01"]                         = "Элементаль Огня",
    ["[Chogal] CD - [Phase 1] Flame Orders_02"]                         = "Появление Адда",
    ["[Chogal] CD - [Phase 1] Shadow Orders_01"]                        = "Элементаль Тьмы'",
    ["[Chogal] CD - [Phase 1] Shadow Orders_02"]                        = "Появление Адда",
    ["[Chogal] CD - [Phase 1] Fury [Tank/Healer]"]                      = GetSpellInfo(82524),
    ["[Chogal] CD - [Phase 1] Adherent"]                                = "Большой Адд",
    ["[Chogal] CD - [Phase 1] Fester Blood"]                            = GetSpellInfo(82299),
    ["[Council] CD - [Phase 1] Glaciate (Feludius)"]                    = "Урон по рейду",
    ["[Council] CD - [Phase 1] Hydro Lance (Feludius) [Healer]"]        = "Урон в цель",
    ["[Council] CD - [Phase 1] Water Bomb (Feludius)"]                  = GetSpellInfo(82699),
    ["[Council] CD - [Phase 1] Aegis of Flames (Ignacious)"]            = "Щит",
    ["[Council] CD - [Phase 1] Gravity Core (Inactive - Arion)"]        = GetSpellInfo(92075),
    ["[Council] CD - [Phase 1] Static Overload (Inactive - Terrastra)"] = GetSpellInfo(92067),
    ["[Council] CD - [Phase 2] Harden Skin (Terrastra)"]                = "Щит",
    ["[Council] CD - [Phase 2] Gravity Well (Terrastra)"]               = GetSpellInfo(83578),
    ["[Council] CD - [Phase 2] Call Winds (Arion)"]                     = GetSpellInfo(83491),
    ["[Council] CD - [Phase 2] Flame Strike (Inactive - Ignacious)"]    = "Огненные Лужи",
    ["[Council] CD - [Phase 3] Gravity Crush"]                          = GetSpellInfo(84948),
    ["[Council] CD - [Phase 3] Lava Seed"]                              = GetSpellInfo(84913),
    ["[T&V] CD - Next Swap"]                                            = "Следующая смена",
    ["[T&V] CD - Twilight Shift [Tank]"]                                = GetSpellInfo(93051),
    ["[T&V] CD - Devouring Flames (Valiona @Ground)"]                   = "Фронтал",
    ["[T&V] CD - Blackout (Valiona @Ground)"]                           = "Рейд Стак",
    ["[T&V] CD - Dazzling Destruction (Theralion @Air)"]                = "Вихревые Круги",
    ["[T&V] CD - Fabulous Flames (Theralion @Ground)"]                  = GetSpellInfo(86505),
    ["[T&V] CD - Engulfing Magic (Theralion @Ground)"]                  = "Дебафф (Выбежать)",
    ["[T&V] CD - Deep Breath (Valiona @Air)"]                           = GetSpellInfo(86059),
    ["[Halifus] CD - Breath"]                                           = "Урон по Рейду",
    ["[Halifus] CD - Shadow Nova"]                                      = "Отбрасывание",
    ["[Halifus] CD - Furious Roar"]                                     = "Тройное Оглушение",
    ["[Halifus] CD - Paralysis"]                                        = "Парализация Босса",

    -- CataRaid_Bastion [Circled Textures]
    ["[Sinestra] Circled Texture_01"] = "Скоро Шары",
    ["[Sinestra] Circled Texture_02"] = "Переключись на Яйца",
    ["[Chogall] Circled Texture_01"]  = "Большие Адды Скоро",
    ["[Chogall] Circled Texture_02"]  = "Готовься Отворачиваться",
    ["[Chogall] Circled Texture_03"]  = "ОТВЕРНИСЬ!",
    ["[Council] Circled Texture_01"]  = GetSpellInfo(84948),
    ["[Council] Circled Texture_02"]  = "Фаза 3 Скоро",
    ["[T&V] Circled Texture_01"]      = "Фронтал Скоро",
    ["[T&V] Circled Texture_02"]      = "Скоро Глубокое Дыхание",
    ["[Halfus] Circled Texture_01"]   = "Парализация Босса Скоро",
    ["[Halfus] Circled Texture_02"]   = "Бей Босса",
    
    -- CataRaid_Bastion [Warnings]
    ["[Sinestra] W - Phase 3"]                                     = "Фаза",
    ["[Sinestra] W - Phase 2"]                                     = "Фаза",
    ["[Sinestra] W - Phase 2 Soon"]                                = "Фаза 2",
    ["[Sinestra] Whelps"]                                          = "Призыв Дракош",
    ["[Chogall] W - Phase 2"]                                      = "Фаза ",
    ["[Chogall] W - 85% Soon"]                                     = "Большой Адд",
    ["[Chogall] Warning - [Phase 1] Spilled Blood"]                = "Слизни Заспавнились",
    ["[Chogall] Warning - [Phase 1] Interrupt Worship"]            = "Сбей Каст МК",
    ["[Chogall] Warning - [Phase 1] Fire Elemental Portal"]        = "Элементаль Огня появился",
    ["[Chogall] Warning - [Phase 1] Shadow Elemental Portal"]      = "Элементаль Тьмы появился",
    ["[Council] Warning - Static Overload"]                         = GetSpellInfo(92067),
    ["[Council] Warning - Gravity Core"]                            = GetSpellInfo(92075),
    ["[Council] Warning - Heart of Ice"]                            = GetSpellInfo(82665),
    ["[Council] Warning - Frost Beacon"]                            = "Сфера Льда",
    ["[Council] W - Phase 3"]                                      = "Фаза",
    ["[Council] W - Phase 2"]                                      = "Фаза",
    ["[T&V] W - Twilight Shift [Tank]"]                            = GetSpellInfo(93051),
    ["[T&V] W - Dazzling Destruction"]                             = "Смотри под ноги",
    ["[T&V] SW - Deep Breath"]                                     = GetSpellInfo(86059),
    ["[T&V] W - Valiona Landed"]                                   = "Валиона Приземляется",
    ["[T&V] W - Theralion Landed"]                                 = "Тералион Приземляется",
    
    -- CataRaid_Bastion [Special Warnings]
    ["[Sinestra] SW - Egg Shield"]                      = "ЯЙЦА В БРОНЕ",
    ["[Sinestra] SW - Eggs Weaken"]                     = "СВИЧ В ЯЙЦА",
    ["[Sinestra] SW - GTFO"]                            = "СВАЛИВАЙ",
    ["[Sinestra] SW - Flame Breath"]                    = GetSpellInfo(90125),
    ["[Chogall] SW - GTFO: Blaze"]                      = "СВАЛИВАЙ",
    ["[Chogall] SW - GTFO: Spilled Blood"]              = "СВАЛИВАЙ",
    ["[Chogall] SW - Adherent Spawn"]                   = "БОЛЬШИЕ АДДЫ",
    ["[Chogall] SW - Corrupting Crash on You"]          = "В ТЕБЯ ЛЕТИТ ШИП!",
    ["[Chogall] SW - Corrupting Crash Near"]            = "ОТОЙДИ",
    ["[Council] SW - Glaciate"]                         = "УРОН ПО РЕЙДУ",
    ["[Council] SW - Aegis of Flame"]                   = GetSpellInfo(82631),
    ["[Council] SW - Dodge Water Bomb"]                 = "УКЛОНЯЙСЯ ОТ БОМБ!",
    ["[Council] SW - Dodge Lava Seeds"]                 = "УКЛОНЯЙСЯ ОТ СЕМЯН",
    ["[Council] SW - Glaciate Range Check_01"]          = "ОТОЙДИ ОТ СИНЕГО БОССА",
    ["[Council] SW - Glaciate Range Check_02"]          = "ОТОЙДИ ОТ СИНЕГО БОССА",
    ["[Council] SW - Glaciate Range Check_03"]          = "ЗАЧИЛЬСЯ, БРАТУШОНОК",
    ["[Council] SW - GTFO"]                             = "СВАЛИВАЙ",
    ["[T&V] SW - GTFO"]                                 = "СВАЛИВАЙ",
    ["[T&V] SW - Twilight Zone"]                        = GetSpellInfo(86214),
    ["[T&V] SW - Wrong Target_01"]                      = "СМЕНИ ТАРГЕТ",
    ["[T&V] SW - Wrong Target_02"]                      = "ВАЛИОНА",
    ["[T&V] SW - Blackout"]                             = "СТАК!",
    ["[T&V] SW - Fabulous Flames On You"]               = "ОГОНЬ НА ТЕБЕ! БЕГИ!",
    ["[T&V] SW - Devouring Flames"]                     = "УКЛОНЯЙСЯ ОТ ФРОНТАЛКИ!",
    ["[Halifus] SW - Furious Roar"]                     = "ТРОЙНОЙ СТАН",
    
    -- CataRaid_Bastion [@Nameplates]
    ["[Sinestra] Face Away"]                              = "Каст фронталки",
    ["[Sinestra] Stop the Cast!"]                         = "Сбей Каст!",
    ["[Chogall] Targetted by Ooze"]                       = "Преследует Тебя",
    ["[Chogall] Mind Controlled"]                         = "Сбей Каст",
    ["[Chogall] Depravity (Adherent Cast)"]               = "Сбей Каст",
    ["[Council] SW - Interrupt Rising Flames"]            = "Сбей Каст",
    ["[Council] SW - Interrupt Harden Skin"]              = "Сбей Каст",
    ["[Trash] Focus Mob (Portal) @Nameplate"]             = "Сбей Каст",
    ["[Trash] I hate this cast please do something"]      = "",
    ["[Sinestra] Indomitable Enrage_01"]                  = "Сдиспель",
    ["[Sinestra] Indomitable Enrage_02"]                  = "Энрага",
    
    -- CataRaid_Bastion [@Nameplates Cooldowns]
    ["[Trash] @Nameplate Cooldowns"]                       = "",
    ["[Sinestra] @Nameplate - Twilight Breath CD"]         = "Фронтал",
    ["[Council] @Nameplate - Flame Torrent CD"]            = "Фронтал",
    ["[Halfus] @Nameplate - Shadow Nova CD"]               = "Откидывание",
    ["[Council] @Nameplate - Inferno Leap CD"]             = "Прыжок",
    ["[Council] @Nameplate - Hydro Lance CD"]              = "Фронтал",
    ["[Council] @Nameplate - Eruption CD"]                 = "Шипы",
    ["[Council] @Nameplate - Disperse CD"]                 = "Телепорт",
    
    -- CataRaid_Bastion [Lists [RL/Assist]]
    ["[Council] Frost Imbued - Counter"]     = "+Урон по Огненному",
    ["[Council] Flame Imbued - Counter"]     = "+Урон по Ледяному",

    -- CataRaid_Bastion [Alternative Widgets]
    ["[Council] Quake_01"]                   = GetSpellInfo(83565),
    ["[Council] Quake_02"]                   = "В ветерок!",
    ["[Council] Thundershock_01"]            = GetSpellInfo(83067),
    ["[Council] Thundershock_02"]            = "В гравитацию!",
}

addonTable.localization.chat['ruRU'] = {
    -- Marks
    ["{rt1}"] = '{Звезда}',
    ["{rt2}"] = '{Круг}',
    ["{rt3}"] = '{Алмаз}',
    ["{rt4}"] = '{Треугольник}',
    ["{rt5}"] = '{Полумесяц}',
    ["{rt6}"] = '{Квадрат}',
    ["{rt7}"] = '{Крест}',
    ["{rt8}"] = '{Череп}',

    -- CataRaid_BWD
    ['Cleared'] = 'Очищено',
    ['cleared'] = 'очищен',
    ['{rt8} RUN OUT! IM STUCKED {rt8}'] = '{rt8} ВЫБЕГИ! Я ОБЕЗДВИЖЕН {rt8}',
    ['{rt8} Frontal on me {rt8}'] = '{rt8} Фронталка в меня {rt8}',
    ['{rt6} AoE {rt6}'] = '{квадрат} АОЕ {квадрат}',
    ['%s AoE %s'] = '%s АОЕ %s',
    ['+Frost Damage'] = 'Раздаю +Урон по Фросту',
    ['+Fire Damage'] = 'Раздаю +Урон по Огню',
    ['{rt6} Frozen Orb {rt6}'] = '{квадрат} Шар на Мне {квадрат}',
    ['{rt1} Out {rt1}'] = '{звезда} Выбегаю {звезда}',
    ['Stack in %d'] = 'Стакайся через %d',

    -- CataRaid_Bastion
    ['{rt8} CRASH ON ME {rt8}'] = '{rt8} СОКРУШЕНИЕ НА МНЕ {rt8}',
    ['{rt8} Flames {rt8}'] = '{rt8} Огонь на мне {rt8}'
}